In [99]:
import pandas as pd
import numpy as np
import re
import tabula
import camelot
import pdfminer
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage
try:
    from cStringIO import StringIO
except ImportError:
    from io import StringIO 
import matplotlib.pyplot as plt

In [100]:
tables=camelot.read_pdf("axis03.pdf",flavor='stream' ,pages = "all",edge_tol=500)            
if len(tables) !=0 :
    df=pd.DataFrame();    tmp=pd.DataFrame(); 
    for i in range(len(tables)) :
        tmp=tables[i].df  
        df=pd.concat([df,tmp]).drop_duplicates(keep='first').reset_index(drop=True)

In [101]:
df.to_csv("error1.csv",index=0)

In [42]:
tmp=tables[2].df
tmp

In [43]:
idx=[ c for c in tmp[tmp.apply(lambda row: row.astype(str).str.lower().str.contains('balance').any(), axis=1) ==True].index if c in tmp[tmp.apply(lambda row: row.astype(str).str.lower().str.contains('date').any(), axis=1) ==True].index ][0]
tmp.columns=tmp.iloc[idx] ; tmp=tmp.iloc[idx+1:,:] ; tmp.reset_index(drop=True,inplace=True) 
print("Columns:",tmp.columns)

Columns: Index(['Tran Date\nValue Date\nTransaction Particulars', 'Chq No.', 'Amount',
       'DR|CR', 'Balance', 'Branch Name'],
      dtype='object', name=0)

In [44]:
tmp=tmp[~tmp.index.isin(tmp[tmp.apply(lambda row: row.astype(str).str.lower().str.contains('page:|account status|total|reason for return|inward clg|opening balance|statement of a/c').any(), axis=1) ==True].index)]
tmp=pd.DataFrame(tmp.T.drop_duplicates().T)
tmp.drop(tmp.nunique(dropna=False)[(tmp.nunique(dropna=False) == 1)].index, axis=1,inplace=True)

In [45]:
tmp.columns = ["A","B","C","D","E"]

In [46]:
# tmp.head()

In [47]:
# tmp.A

In [91]:
tmp1 = pd.DataFrame(tmp.A.str.split('\n',2).tolist(),columns=["Z1", "Z2", "Z3"])

In [92]:
tmp1

,Z1,Z2,Z3
0,,None,None
1,14-01-2019,14-01-2019,EDC/00053-00053-/M037011032984700
2,,None,None
3,,None,None
4,14-01-2019,14-01-2019,IMPS/P2A/901412924696/919971624523/INETIMPS00073
5,,None,None
6,,None,None
7,14-01-2019,14-01-2019,IMPS/P2A/901412927199/919971624523/MOBUA01304940
8,,None,None
9,,None,None
10,14-01-2019,14-01-2019,IMPS/P2A/901412321960/0831010104411UTBI0MBZC45/
11,,None,None
12,,None,None
13,15-01-2019,15-01-2019,ECOM PUR/PAYTM/Noida/150119/10:25
14,,None,None
15,BY CASH DEPOSIT-,None,None
16,17-01-2019,17-01-2019,None
17,BNA/DPRH329801/6971/170119/SOUTH D,None,None
18,,None,None
19,17-01-2019,17-01-2019,IMPS/P2A/901713217651/62246765390SBIN0001078/
20,,None,None
21,,None,None
22,21-01-2019,21-01-2019,EDC/00054-00054-/M037011032984700
23,,None,None
24,,None,None
25,22-01-2019,22-01-2019,EDC/00055-00055-/M037011032984700
26,,None,None
27,,None,None
28,22-01-2019,22-01-2019,ECOM PUR/PAYTM/1204770770/220119/13:26
29,,None,None
30,BY CASH DEPOSIT-,None,None
31,23-01-2019,23-01-2019,None
32,BNA/DPRH329801/8113/230119/SOUTH D,None,None
33,BY CASH DEPOSIT-,None,None
34,23-01-2019,23-01-2019,None
35,BNA/DPRH329801/8115/230119/SOUTH D,None,None
36,,None,None
37,24-01-2019,24-01-2019,ECOM PUR/PTM*PAYTM/NOIDA/240119/17:50
38,,None,None
39,,None,None
40,28-01-2019,28-01-2019,EDC/00056-00056-/M037011032984700
41,,None,None
42,BY CASH DEPOSIT-,None,None
43,28-01-2019,28-01-2019,None
44,BNA/DPRH329801/8913/280119/SOUTH D,None,None

In [93]:
tmp1.replace(r'^\s*$', np.nan, regex=True, inplace=True)
tmp1.fillna(value=pd.np.nan, inplace=True)
# match = re.search(r'(\d+-\d+-\d+)',i)
# match.group(1)

In [94]:
tmp1

,Z1,Z2,Z3
0,NaN,NaN,NaN
1,14-01-2019,14-01-2019,EDC/00053-00053-/M037011032984700
2,NaN,NaN,NaN
3,NaN,NaN,NaN
4,14-01-2019,14-01-2019,IMPS/P2A/901412924696/919971624523/INETIMPS00073
5,NaN,NaN,NaN
6,NaN,NaN,NaN
7,14-01-2019,14-01-2019,IMPS/P2A/901412927199/919971624523/MOBUA01304940
8,NaN,NaN,NaN
9,NaN,NaN,NaN
10,14-01-2019,14-01-2019,IMPS/P2A/901412321960/0831010104411UTBI0MBZC45/
11,NaN,NaN,NaN
12,NaN,NaN,NaN
13,15-01-2019,15-01-2019,ECOM PUR/PAYTM/Noida/150119/10:25
14,NaN,NaN,NaN
15,BY CASH DEPOSIT-,NaN,NaN
16,17-01-2019,17-01-2019,NaN
17,BNA/DPRH329801/6971/170119/SOUTH D,NaN,NaN
18,NaN,NaN,NaN
19,17-01-2019,17-01-2019,IMPS/P2A/901713217651/62246765390SBIN0001078/
20,NaN,NaN,NaN
21,NaN,NaN,NaN
22,21-01-2019,21-01-2019,EDC/00054-00054-/M037011032984700
23,NaN,NaN,NaN
24,NaN,NaN,NaN
25,22-01-2019,22-01-2019,EDC/00055-00055-/M037011032984700
26,NaN,NaN,NaN
27,NaN,NaN,NaN
28,22-01-2019,22-01-2019,ECOM PUR/PAYTM/1204770770/220119/13:26
29,NaN,NaN,NaN
30,BY CASH DEPOSIT-,NaN,NaN
31,23-01-2019,23-01-2019,NaN
32,BNA/DPRH329801/8113/230119/SOUTH D,NaN,NaN
33,BY CASH DEPOSIT-,NaN,NaN
34,23-01-2019,23-01-2019,NaN
35,BNA/DPRH329801/8115/230119/SOUTH D,NaN,NaN
36,NaN,NaN,NaN
37,24-01-2019,24-01-2019,ECOM PUR/PTM*PAYTM/NOIDA/240119/17:50
38,NaN,NaN,NaN
39,NaN,NaN,NaN
40,28-01-2019,28-01-2019,EDC/00056-00056-/M037011032984700
41,NaN,NaN,NaN
42,BY CASH DEPOSIT-,NaN,NaN
43,28-01-2019,28-01-2019,NaN
44,BNA/DPRH329801/8913/280119/SOUTH D,NaN,NaN

In [95]:
tmp1["flag"] = tmp1["Z2"].astype(str)+tmp1["Z3"].astype(str)

In [96]:
tmp1

,Z1,Z2,Z3,flag
0,NaN,NaN,NaN,nannan
1,14-01-2019,14-01-2019,EDC/00053-00053-/M037011032984700,14-01-2019EDC/00053-00053-/M037011032984700
2,NaN,NaN,NaN,nannan
3,NaN,NaN,NaN,nannan
4,14-01-2019,14-01-2019,IMPS/P2A/901412924696/919971624523/INETIMPS00073,14-01-2019IMPS/P2A/901412924696/919971624523/I...
5,NaN,NaN,NaN,nannan
6,NaN,NaN,NaN,nannan
7,14-01-2019,14-01-2019,IMPS/P2A/901412927199/919971624523/MOBUA01304940,14-01-2019IMPS/P2A/901412927199/919971624523/M...
8,NaN,NaN,NaN,nannan
9,NaN,NaN,NaN,nannan
10,14-01-2019,14-01-2019,IMPS/P2A/901412321960/0831010104411UTBI0MBZC45/,14-01-2019IMPS/P2A/901412321960/0831010104411U...
11,NaN,NaN,NaN,nannan
12,NaN,NaN,NaN,nannan
13,15-01-2019,15-01-2019,ECOM PUR/PAYTM/Noida/150119/10:25,15-01-2019ECOM PUR/PAYTM/Noida/150119/10:25
14,NaN,NaN,NaN,nannan
15,BY CASH DEPOSIT-,NaN,NaN,nannan
16,17-01-2019,17-01-2019,NaN,17-01-2019nan
17,BNA/DPRH329801/6971/170119/SOUTH D,NaN,NaN,nannan
18,NaN,NaN,NaN,nannan
19,17-01-2019,17-01-2019,IMPS/P2A/901713217651/62246765390SBIN0001078/,17-01-2019IMPS/P2A/901713217651/62246765390SBI...
20,NaN,NaN,NaN,nannan
21,NaN,NaN,NaN,nannan
22,21-01-2019,21-01-2019,EDC/00054-00054-/M037011032984700,21-01-2019EDC/00054-00054-/M037011032984700
23,NaN,NaN,NaN,nannan
24,NaN,NaN,NaN,nannan
25,22-01-2019,22-01-2019,EDC/00055-00055-/M037011032984700,22-01-2019EDC/00055-00055-/M037011032984700
26,NaN,NaN,NaN,nannan
27,NaN,NaN,NaN,nannan
28,22-01-2019,22-01-2019,ECOM PUR/PAYTM/1204770770/220119/13:26,22-01-2019ECOM PUR/PAYTM/1204770770/220119/13:26
29,NaN,NaN,NaN,nannan
30,BY CASH DEPOSIT-,NaN,NaN,nannan
31,23-01-2019,23-01-2019,NaN,23-01-2019nan
32,BNA/DPRH329801/8113/230119/SOUTH D,NaN,NaN,nannan
33,BY CASH DEPOSIT-,NaN,NaN,nannan
34,23-01-2019,23-01-2019,NaN,23-01-2019nan
35,BNA/DPRH329801/8115/230119/SOUTH D,NaN,NaN,nannan
36,NaN,NaN,NaN,nannan
37,24-01-2019,24-01-2019,ECOM PUR/PTM*PAYTM/NOIDA/240119/17:50,24-01-2019ECOM PUR/PTM*PAYTM/NOIDA/240119/17:50
38,NaN,NaN,NaN,nannan
39,NaN,NaN,NaN,nannan
40,28-01-2019,28-01-2019,EDC/00056-00056-/M037011032984700,28-01-2019EDC/00056-00056-/M037011032984700
41,NaN,NaN,NaN,nannan
42,BY CASH DEPOSIT-,NaN,NaN,nannan
43,28-01-2019,28-01-2019,NaN,28-01-2019nan
44,BNA/DPRH329801/8913/280119/SOUTH D,NaN,NaN,nannan

In [98]:
tmp1.to_csv("tmp1.csv", index=0)

In [85]:
idx= c for c in tmp1[tmp1.apply(lambda row: row.astype(str).str.lower().str.contains('nan').any(), axis=1) ==True].index

SyntaxError: invalid syntax (<ipython-input-85-26938af588b8>, line 1)

In [79]:
tmp1['flag']=tmp1['flag'].apply(lambda row : np.nan if 'nan' in row else row)

In [70]:
tmp1.to_csv("tmp11.csv", index=0)